Requisitos-de-Software/2021.1-DisneyPlus

docs/apresentações/apresentação-1.md, docs/apresentações/apresentação-2.md, mkdocs.yml
=> feat: add presentation docs

docs/elicitacao/moscow.md
Adicionei a documentação da priorização de MoSCoW
=> Add MoSCoW docs

Dockerfile, docker-compose.yml, mkdocs.yml
- Criação de container para o projeto utilizando docker.
- Clone o repositório
- Execute docker-compose up
- :))
=> compose for project

docs/elicitacao/moscow.md
- Correções no artefato de moscow.
- Revisar documento.
=> fix: update moscow doc

docs/planejamento/cronograma.md
- Correção no histórico de versão.
- Revisar documento.
=> fix: fix version history

docs/elicitacao/brainstorm.md, docs/elicitacao/introspeccao.md, docs/elicitacao/observacao.md, mkdocs.yml
- Criada página de técnica de elecitação observação
- Página adicionada a paginação do mkdocs
- Adicionado tópico de versionamento nas páginas de brainstorming e instropecção
- Verifique os arquivos alterados
=> added observation method page

docs/elicitacao/personas.md
- Adicionando antipersona José.
- Revise.
=> add antipersona

docs/elicitacao/tecnicas/observacao.md
- Corrigi o paragrafo de descrição no tópico de observação
=> fix definition docs

docs/elicitacao/tecnicas/questionario.md
- Adicionar descrição as perguntas do questionário
=> Adicionar descrição as perguntas do questionário

docs/modelagem/backlog/backlog.md, mkdocs.yml
- Adiciona menu da parte de backlog e as histórias de usuário
=> Adiciona Product Backlog

docs/modelagem/backlog/backlog.md
- Adicionada introdução do backlog e descrição sobre épicos e histórias de usuário
- Verifique os arquivos alterados e seus conteúdos
=> Added backlog descriptions and references

docs/modelagem/backlog/backlog.md
- Adicionada referência do TRT9
- Verificar arquivos modificados
=> Added trt9 reference

docs/apresentacoes/apresentacao4.md, mkdocs.yml
- Adição da apresentação 4.
- Revisar código;
- Revisar Wiki.
=> doc: add presentation 4 document

docs/analise/verificacao/cenarios.md
- Adicionado verificação 
- Verificar arquivos modificados
=> Added verificacao of cenario c01

docs/apresentacoes/apresentacao5.md, mkdocs.yml
- Adição da apresentação 5.
- Revisar documento;
- Revisar wiki.
=> doc: add presentation 5

docs/analise/verificacao/cenarios.md
- Adicionado verificação de todos os cenários
- Analisar os documentos modificados
=> adicionado verificacao de todos os cenarios

docs/analise/verificacao/backlog.md, docs/analise/verificacao/cenarios.md, docs/analise/verificacao/lexicos.md, docs/analise/verificacao/nfr_framework.md, docs/analise/verificacao/rich_picture.md
- Correção na formatação dos arquivos de verificação.
- Revisar documentos;
- Revisar wiki.
=> fix: format verification documents

docs/analise/verificacao/backlog.md, docs/analise/verificacao/casos_de_uso.md, docs/analise/verificacao/cenarios.md, docs/analise/verificacao/nfr_framework.md, docs/analise/verificacao/rich_picture.md
- Atualiza estilo das tabelas de verificação.
=> Atualiza estilo da tabela de verificação

docs/analise/validacao/prototipacao.md
- Adicionei o protótipo do figma ao documento de prototipação
- Subir wiki e ver o doc de prototipação
=> Add figma prototype

docs/analise/verificacao/casos_de_uso.md
- Atualiza verificação de casos de uso
=> Atualiza verificação de casos de uso

docs/apresentacoes/apresentacao1.md, docs/pos_rastreabilidade/backward_from.md, docs/pre_rastreabilidade/rich_pictures.md, mkdocs.yml
- Adiciona documentação Backward-from em Pós-Rastreabilidade
=> Adiciona documentação Backward-from em Pós-Rastreabilidade

docs/apresentacoes/apresentacao6.md, mkdocs.yml
- Adição da apresentação 6.
- Revisar markdown;
- Revisar vídeo e slides;
- Revisar integridade da wiki.
=> doc: add presentation 6
